package co.casterlabs.koi.clientid;

public enum ClientIdScope {
    USER_AUTH,
    USER_SEND_CHAT,
    USER_UPVOTE_MESSAGE,
    USER_DELETE_MESSAGE,
    USER_CREDENTIALS,
    USER_PUPPET_AUTH,

    STREAM_STATUS,
    WILDCARD_STREAM_STATUS,

    BROADCAST_MESSAGE,
    BROADCAST_BANNER,

}
