package co.casterlabs.koi.networking.outgoing;

public enum OutgoingMessageErrorType {
    SERVER_INTERNAL_ERROR,
    SERVER_API_ERROR,

    NOT_IMPLEMENTED,

    FAILED_KEEP_ALIVE,

    REQUEST_TYPE_INVAID,
    REQUEST_JSON_INVAID,
    REQUEST_CRITERIA_INVAID,

    USER_ALREADY_PRESENT,
    USER_INVALID,
    USER_PLATFORM_INVALID,
    USER_NOT_AUTHORIZED,
    USER_AUTH_INVALID,

    PUPPET_USER_NOT_AUTHORIZED,
    PUPPET_AUTH_INVALID,

    ;
}
