package co.casterlabs.koi.networking;

public enum RequestError {
    SERVER_INTERNAL_ERROR,
    SERVER_API_ERROR,

    NOT_IMPLEMENTED,

    REQUEST_TYPE_INVAID,
    REQUEST_JSON_INVAID,
    REQUEST_CRITERIA_INVAID,

    USER_ALREADY_PRESENT,
    USER_INVALID,
    USER_NOT_AUTHORIZED,
    AUTH_INVALID,

    ;
}
